name: consumer
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: test-topic
    required: false
  - name: consumergroup
    inputType: FreeText
    description: ''
    defaultValue: v21
    required: false
  - name: role
    inputType: FreeText
    description: ''
    defaultValue: A
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
