name: AI Customer
language: python
variables:
  - name: input
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: customer-topic
    required: true
  - name: conversation_length
    inputType: FreeText
    description: Maximum conversation length, after which the conversation resets.
    defaultValue: 15
    required: true
  - name: output
    inputType: InputTopic
    description: ''
    defaultValue: agent-topic
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
