name: Chatbot
language: python
variables:
  - name: topic
    inputType: OutputTopic
    description: Chat topic
    defaultValue: ''
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
