name: Chatbot
language: python
variables:
  - name: topic
    inputType: OutputTopic
    description: Chat topic
    defaultValue: ai-chat-history
    required: true
  - name: role
    inputType: FreeText
    description: 'Chatbot role: AGENT, CUSTOMER'
    defaultValue: ''
    required: true
  - name: product
    inputType: FreeText
    description: Product name.
    defaultValue: Roomba vacuum cleaner
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
