name: StatePeeker
language: python
variables:
  - name: topic
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: test-topic
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
